# Site settings
ref: CSCC69
title: Operating systems
edition: Summer 2020
description: "Principles of operating systems. The operating system as a control program and as a resource allocator. The concept of a process and concurrency problem: synchronization, mutual exclusion, deadlock. Additional topics include memory management, file systems, process scheduling, threads, and protection."
website: https://thierrysans.me/CSCC69/
github: https://github.com/ThierrySans/CSCC69
piazza: https://piazza.com/mail.utoronto.ca/summer2020/cscc69
feedback: https://forms.gle/kksJCc48sYKUwP4y7

instructor:
  name: Thierry Sans
  email: "&#116;&#104;&#105;&#101;&#114;&#114;&#121;&#46;&#115;&#97;&#110;&#115;&#64;&#117;&#116;&#111;&#114;&#111;&#110;&#116;&#111;&#46;&#99;&#97;"
  website: https://thierrysans.github.io/
  github: ThierrySans
  twitter: ThierrySans
  hours: Thu 11-12
  location: online
  contact: Piazza only (no mail)
  role: LEC

# https://www.fingerlakesbmw.org/main/flobfuscate.php
assistants:
    - name: Jayden Arquelada
      role:  TUT04
      contact: "&#106;&#97;&#121;&#100;&#101;&#110;&#46;&#97;&#114;&#113;&#117;&#101;&#108;&#97;&#100;&#97;&#64;&#109;&#97;&#105;&#108;&#46;&#117;&#116;&#111;&#114;&#111;&#110;&#116;&#111;&#46;&#99;&#97;"
      hours: Mon 5-6
      location: online
    - name: Jun Zheng
      role:  TUT03
      contact: "&#106;&#117;&#110;&#46;&#122;&#104;&#101;&#110;&#103;&#64;&#109;&#97;&#105;&#108;&#46;&#117;&#116;&#111;&#114;&#111;&#110;&#116;&#111;&#46;&#99;&#97;"
      hours: Wed 6-7pm
      location: online
    - name: Mohamed Moustafa
      role:  TUT01
      contact: "&#109;&#111;&#104;&#97;&#109;&#109;&#97;&#100;&#46;&#109;&#111;&#117;&#115;&#116;&#97;&#102;&#97;&#64;&#109;&#97;&#105;&#108;&#46;&#117;&#116;&#111;&#114;&#111;&#110;&#116;&#111;&#46;&#99;&#97;"
      hours: Thu 1-2pm
      location: online
    - name: Spencer McCoubrey
      role:  TUT02
      contact: "&#115;&#112;&#101;&#110;&#99;&#101;&#114;&#46;&#109;&#99;&#99;&#111;&#117;&#98;&#114;&#101;&#121;&#64;&#109;&#97;&#105;&#108;&#46;&#117;&#116;&#111;&#114;&#111;&#110;&#116;&#111;&#46;&#99;&#97;"
      hours: Tue 4-5pm
      location: online
  
timings:
    - section: Lecture 98 & 99
      time: Wed 12:00-14:00
      location: online
    - section: TUT01
      time: Wed 15:00-16:00
      location: online
    - section: TUT02
      time: Wed 11:00-12:00
      location: online
    - section: TUT03
      time: Fri 10:00-11:00
      location: online
    - section: TUT04
      time: Fri 11:00-12:00
      location: online
        
first: 20200511