# Site settings
ref: CSCC69
title: Operating systems
edition: Winter 2021
description: "Principles of operating systems. The operating system as a control program and as a resource allocator. The concept of a process and concurrency problem: synchronization, mutual exclusion, deadlock. Additional topics include memory management, file systems, process scheduling, threads, and protection."
website: https://thierrysans.me/CSCC69/
github: https://github.com/ThierrySans/CSCC69
piazza: https://piazza.com/utoronto.ca/winter2021/cscc69
feedback: https://forms.gle/JV82AQsJDv8Wj2zt7

instructor:
  name: Thierry Sans
  email: "&#116;&#104;&#105;&#101;&#114;&#114;&#121;&#46;&#115;&#97;&#110;&#115;&#64;&#117;&#116;&#111;&#114;&#111;&#110;&#116;&#111;&#46;&#99;&#97;"
  website: https://thierrysans.github.io/
  github: ThierrySans
  twitter: ThierrySans
  hours: TBD
  location: <a href="https://utoronto.zoom.us/j/81908690391">Zoom</a>
  contact: Piazza only (no mail)
  role: LEC

# https://www.fingerlakesbmw.org/main/flobfuscate.php
assistants:
    - name: Anh Le
      role:  T05
      contact: "&#105;&#111;&#97;&#110;&#104;&#46;&#108;&#101;&#64;&#109;&#97;&#105;&#108;&#46;&#117;&#116;&#111;&#114;&#111;&#110;&#116;&#111;&#46;&#99;&#97;"
      hours: TBD
      location: <a href="https://utoronto.zoom.us/j/81908690391">Zoom</a> 
    - name: David Yue
      role:  T02
      contact: "&#100;&#97;&#118;&#105;&#100;&#46;&#121;&#117;&#101;&#64;&#109;&#97;&#105;&#108;&#46;&#117;&#116;&#111;&#114;&#111;&#110;&#116;&#111;&#46;&#99;&#97;"
      hours: TBD
      location: <a href="https://utoronto.zoom.us/j/81908690391">Zoom</a>
    - name: Jun Zheng
      role:  T03
      contact: "&#106;&#117;&#110;&#46;&#122;&#104;&#101;&#110;&#103;&#64;&#109;&#97;&#105;&#108;&#46;&#117;&#116;&#111;&#114;&#111;&#110;&#116;&#111;&#46;&#99;&#97;"
      hours: TBD
      location: <a href="https://utoronto.zoom.us/j/81908690391">Zoom</a>
    - name: Qibo Wang
      role:  T01
      contact: "&#113;&#105;&#98;&#111;&#46;&#119;&#97;&#110;&#103;&#64;&#109;&#97;&#105;&#108;&#46;&#117;&#116;&#111;&#114;&#111;&#110;&#116;&#111;&#46;&#99;&#97;"
      hours: TBD
      location: <a href="https://utoronto.zoom.us/j/81908690391">Zoom</a>
    - name: Swarup Srinivasan
      role:  T04
      contact: "&#115;&#119;&#97;&#114;&#117;&#112;&#46;&#115;&#114;&#105;&#110;&#105;&#118;&#97;&#115;&#97;&#110;&#64;&#117;&#116;&#111;&#114;&#111;&#110;&#116;&#111;&#46;&#99;&#97;"
      hours: TBD
      location: <a href="https://utoronto.zoom.us/j/81908690391">Zoom</a>      
  
timings:
    - section: LEC01
      time: Fri 9:00-11:00
      location: <a href="https://utoronto.zoom.us/j/81908690391">Zoom</a>
    - section: TUT01
      time: Mon 10:00-11:00
      location: <a href="https://utoronto.zoom.us/j/81908690391">Zoom</a>
    - section: TUT02
      time: Mon 11:00-12:00
      location: <a href="https://utoronto.zoom.us/j/81908690391">Zoom</a>
    - section: TUT03
      time: Tue 17:00-18:00
      location: <a href="https://utoronto.zoom.us/j/81908690391">Zoom</a>
    - section: TUT04
      time: Tue 16:00-17:00
      location: <a href="https://utoronto.zoom.us/j/81908690391">Zoom</a>
    - section: TUT05
      time: Tue 9:00-11:00
      location: <a href="https://utoronto.zoom.us/j/81908690391">Zoom</a>
        
first: 20210113