# Site settings
ref: CSCC69
title: Operating systems
edition: Summer 2021
description: "Principles of operating systems. The operating system as a control program and as a resource allocator. The concept of a process and concurrency problem: synchronization, mutual exclusion, deadlock. Additional topics include memory management, file systems, process scheduling, threads, and protection."
website: https://thierrysans.me/CSCC69/
github: https://github.com/ThierrySans/CSCC69
piazza: https://piazza.com/utoronto.ca/summer2021/cscc69
feedback: https://forms.gle/9Qqy1vt5WSCqAysC7

instructor:
  name: Thierry Sans
  email: "&#116;&#104;&#105;&#101;&#114;&#114;&#121;&#46;&#115;&#97;&#110;&#115;&#64;&#117;&#116;&#111;&#114;&#111;&#110;&#116;&#111;&#46;&#99;&#97;"
  website: https://thierrysans.github.io/
  github: ThierrySans
  twitter: ThierrySans
  hours: Fri 2-3 PM
  location: <a href="https://utoronto.zoom.us/j/88149611289">Zoom</a>
  contact: Piazza only (no mail)
  role: Prof.

# https://www.fingerlakesbmw.org/main/flobfuscate.php
assistants:
    - name: Jiasong Liang
      role:  TA
      contact: "&#106;&#105;&#97;&#115;&#111;&#110;&#103;&#46;&#108;&#105;&#97;&#110;&#103;&#64;&#109;&#97;&#105;&#108;&#46;&#117;&#116;&#111;&#114;&#111;&#110;&#116;&#111;&#46;&#99;&#97;"
      hours: Thu 3-4 PM
      location: <a href="https://utoronto.zoom.us/j/81841578311">Zoom</a>
    - name: Qibo Wang
      role:  TA
      contact: "&#113;&#105;&#98;&#111;&#46;&#119;&#97;&#110;&#103;&#64;&#109;&#97;&#105;&#108;&#46;&#117;&#116;&#111;&#114;&#111;&#110;&#116;&#111;&#46;&#99;&#97;"
      hours: Wed 10-11 AM
      location: <a href="https://utoronto.zoom.us/j/83595177763">Zoom</a>
    - name: Jun Zheng
      role:  TA
      contact: "&#106;&#117;&#110;&#46;&#122;&#104;&#101;&#110;&#103;&#64;&#109;&#97;&#105;&#108;&#46;&#117;&#116;&#111;&#114;&#111;&#110;&#116;&#111;&#46;&#99;&#97;"
      hours: Tue 3-4 PM
      location: <a href="https://utoronto.zoom.us/j/83307840255">Zoom</a>
    - name: Tahmid Haque
      role:  TA
      contact: "&#116;&#97;&#104;&#109;&#105;&#100;&#46;&#104;&#97;&#113;&#117;&#101;&#64;&#109;&#97;&#105;&#108;&#46;&#117;&#116;&#111;&#114;&#111;&#110;&#116;&#111;&#46;&#99;&#97;"
      hours: Mon 12-1 PM
      location: <a href="https://utoronto.zoom.us/j/87601413644">Zoom</a>
  
timings:
    - section: LEC01
      time: Fri 11:00-13:00
      location: <a href="https://utoronto.zoom.us/j/81908690391">Zoom</a>
      instructor: Thierry Sans
    - section: TUT01
      time: Mon 15:00-16:00
      location: <a href="https://utoronto.zoom.us/j/85898278946">Zoom</a>
      instructor: Jun Zheng
    - section: TUT02
      time: Thu 16:00-17:00
      location: <a href="https://utoronto.zoom.us/j/87986962625">Zoom</a>
      instructor: Jiasong Liang
    - section: TUT03
      time: Thu 17:00-18:00
      location: <a href="https://utoronto.zoom.us/j/83049209249">Zoom</a>
      instructor: Tahmid Haque
    - section: TUT04
      time: Wed 09:00-10:00
      location: <a href="https://utoronto.zoom.us/j/81288678635">Zoom</a>
      instructor: Qibo Wang
        
first: 20210502