# Site settings
ref: CSCC69
title: Operating systems
edition: Winter 2022
description: "Principles of operating systems. The operating system as a control program and as a resource allocator. The concept of a process and concurrency problem: synchronization, mutual exclusion, deadlock. Additional topics include memory management, file systems, process scheduling, threads, and protection."
website: https://thierrysans.me/CSCC69/
github: https://github.com/ThierrySans/CSCC69
piazza: https://piazza.com/utoronto.ca/winter2022/cscc69
feedback: https://forms.gle/XgCKgoXeaLFY9KrC6

instructor:
  name: Thierry Sans
  email: "&#116;&#104;&#105;&#101;&#114;&#114;&#121;&#46;&#115;&#97;&#110;&#115;&#64;&#117;&#116;&#111;&#114;&#111;&#110;&#116;&#111;&#46;&#99;&#97;"
  website: https://thierrysans.github.io/
  github: ThierrySans
  twitter: ThierrySans
  hours: Thu 10 AM - 11 AM
  location: <a href="https://utoronto.zoom.us/j/88149611289">Zoom</a> 
  contact: Piazza only (no email)

# https://www.fingerlakesbmw.org/main/flobfuscate.php
assistants:
    - name: Aryan Thakur
      contact: "&#97;&#114;&#121;&#97;&#110;&#46;&#116;&#104;&#97;&#107;&#117;&#114;&#64;&#109;&#97;&#105;&#108;&#46;&#117;&#116;&#111;&#114;&#111;&#110;&#116;&#111;&#46;&#99;&#97;"
      hours: Wed 5 PM - 6 PM
      location: <a href="https://utoronto.zoom.us/j/82516023507">Zoom</a>
    - name: Qibo Wang
      contact: "&#113;&#105;&#98;&#111;&#46;&#119;&#97;&#110;&#103;&#64;&#109;&#97;&#105;&#108;&#46;&#117;&#116;&#111;&#114;&#111;&#110;&#116;&#111;&#46;&#99;&#97;"
      hours: Mon 10 AM - 11 AM
      location: <a href="https://utoronto.zoom.us/j/89832057654">Zoom</a>
    - name: Tahmid Haque
      contact: "&#116;&#97;&#104;&#109;&#105;&#100;&#46;&#104;&#97;&#113;&#117;&#101;&#64;&#109;&#97;&#105;&#108;&#46;&#117;&#116;&#111;&#114;&#111;&#110;&#116;&#111;&#46;&#99;&#97;"
      hours: Tue 2 PM - 3 PM
      location: <a href="https://utoronto.zoom.us/j/87500553348">Zoom</a>
  
timings:
    - section: LEC01
      time: Fri 9:00-11:00
      location: <a href="https://utoronto.zoom.us/j/81646366886">Zoom</a>
      instructor: Thierry Sans
    - section: TUT01
      time: Mon 10:00-11:00
      location: <a href="https://utoronto.zoom.us/j/84691756212">Zoom</a>
      instructor: Qibo Wang
    - section: TUT03
      time: Tue 16:00-17:00
      location: <a href="https://utoronto.zoom.us/j/85193106642">Zoom</a>
      instructor: Tahmid Haque
    - section: TUT04
      time: Thu 17:00-18:00
      location: <a href="https://utoronto.zoom.us/j/86425770950">Zoom</a>
      instructor: Aryan Thakur
        
first: 20220110